- hosts: all
  become: true
  tasks:
    - name: delete old deployment
      command: kubectl delete -f /home/ubuntu/Deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
    - name: delete old service
      command: kubectl delete -f /home/ubuntu/Service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
    - name: create new deployment
      command: kubectl apply -f /home/ubuntu/deployment.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
    - name: create new service
      command: kubectl apply -f /home/ubuntu/service.yml
      environment:
        KUBECONFIG: /home/ubuntu/.kube/config
